const app= require('express')
const { cargarActividades, cargahome, cargarForos, cargarFormularioCultivos, cargaformularioCosechas }=require('../Controllers/CargaControllers')
const { agregarPost, leerPublicaciones } = require('../Controllers/HomeControllers')
const Verificaruser = require('../Middleware/Verificaruser')
const { insertarCosecha, insertarPlantacion, obtenerCosechas, obtenerPlantaciones, insertarCultivo } = require('../Controllers/ActividadesControllers')
const router=app.Router()
router.get('/principal',Verificaruser,leerPublicaciones)
router.get('/Acciones',Verificaruser,cargarActividades)
router.get('/Foros',Verificaruser,cargarForos)
router.post('/principal',Verificaruser,agregarPost)
router.get('/yolo',Verificaruser,leerPublicaciones)
router.post('/cosecha',Verificaruser,insertarCosecha)
router.post('/agregarCultivo',Verificaruser,insertarCultivo)
router.get('/cosecha',Verificaruser,cargaformularioCosechas)
router.get('/agregarCultivo',Verificaruser,cargarFormularioCultivos)
router.get('/tablaCosecha',Verificaruser,obtenerCosechas)
router.get('/tablaCultivo',Verificaruser,obtenerPlantaciones)
module.exports= router